stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  - release

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-staging-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: staging
  script:
    - echo "Deploying staging build..."
    - echo "Staging build successfully deployed."
  only:
    - staging

deploy-main-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying main build..."
    - echo "Main build successfully deployed."
  only:
    - main

release-job:
  image: node
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab
    - npm install semantic-release-discord-bot -D
  variables: 
    SEMANTIC_RELEASE_PACKAGE: $CI_PROJECT_NAME
  script:
    - semantic-release
  only:
    - main
